/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.text.*;
import java.awt.print.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Koneksi;

/**
 *
 * @author blackhat
 */
public class data_inventaris extends javax.swing.JFrame {

    /**
     * Creates new form data_inventaris
     */

    public data_inventaris() throws SQLException {
        initComponents();
        tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelinventaris = new javax.swing.JTable();
        btprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selamat Datang di Menu Data Inventaris");

        jLabel2.setText("Data Inventaris Rumah Sakit");

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        bttambah.setText("Tambah Data");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        tabelinventaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Inventaris", "Tanggal Masuk", "Supplier", "Kategori", "Merek", "Kondisi", "Type", "Jumlah"
            }
        ));
        tabelinventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelinventarisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelinventaris);

        btprint.setText("cetak");
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 542, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttambah)
                                .addGap(0, 725, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bthapus))
                                    .addComponent(btback, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btprint)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btedit)
                    .addComponent(bthapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btback)
                .addGap(80, 80, 80)
                .addComponent(btprint)
                .addGap(29, 29, 29))
        );

        setSize(new java.awt.Dimension(863, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
tambah_data_inventaris a = new tambah_data_inventaris();
    a.setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
       dashboard a = new dashboard();
       a.setVisible(true);
       dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
edit_data_inventaris a = new edit_data_inventaris();
a.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void tabelinventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelinventarisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelinventarisMouseClicked

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
int row=tabelinventaris.getSelectedRow();
        String nama=(String) tabelinventaris.getValueAt(row, 0);
        model.model_data_inventaris mod=new model.model_data_inventaris();
        try {
            mod.hapusdata(nama);
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(data_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
        try {
            new data_inventaris().setVisible(true);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(data_inventaris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
  MessageFormat header = new MessageFormat("Data Inventaris");
  MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
        try
  {
      tabelinventaris.print(JTable.PrintMode.NORMAL, header, footer);
  }catch(java.awt.print.PrinterException e)
  {
      System.err.format("cannot print",e.getMessage());
  }
    }//GEN-LAST:event_btprintActionPerformed

    public void tampildata() throws SQLException
   {
       DefaultTableModel dtm;
       Connection con = (Connection)Koneksi.getKoneksi();
      try{
         Object [] rows={"Nama Inventaris,","Tanggal Masuk","Supplier", "Kategori"," Merk"," Kondisi", "Type"," Jumlah"};
            dtm=new DefaultTableModel(null,rows);
           tabelinventaris.setModel(dtm);
            tabelinventaris.setBorder(null);
            int no = 1;
            String inven = "";
            String tanggal = "";
            String supli = "";
            String kate = "";
            String merek = "";
            String kondi = "";
            String type = "";
            String jumlah = "";
            try{
              String sql="select namaInventaris,tanggalmasuk,namaSupplier,jenisKategori,namaMerk,jenisKondisi,type,jumlah FROM data_inventaris";
              Statement st=con.createStatement();
              ResultSet rs=st.executeQuery(sql);
                while(rs.next()){
                   inven = rs.getString("namaInventaris");
                   tanggal = rs.getString("tanggalmasuk");
                   supli = rs.getString("namaSupplier");
                   kate = rs.getString("jenisKategori");
                   merek = rs.getString("namaMerk");
                   kondi = rs.getString("jenisKondisi");
                   type = rs.getString("type");
                   jumlah = rs.getString("jumlah");

                    String [] tampil={inven,tanggal,supli,kate,merek,kondi,type,jumlah};
                    dtm.addRow(tampil);
                }
            }catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Query Salah "+e);

            }
        }catch(Exception e){
            e.printStackTrace();

        }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new data_inventaris().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(data_kategori.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btprint;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelinventaris;
    // End of variables declaration//GEN-END:variables
}
